### ISSUE TITLE
Linter giving false results

### ISSUE THREAD

**Issue by SomeshPatil** [jfcherng/SublimeLinter-contrib-gcc#13]
Iam using  gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) . The linter give gcc:error stray "\(some numbers" in program error. In the #include statements.
Here is the list of errors shown on using #include<bits/stdc++.h> 
nqueen.cpp:
     1:1    error            gcc:error        stray '\177' in program
     1:1    error            gcc:error        stray '\1' in program
     1:1    error            gcc:error        stray '\7' in program
     1:1    error            gcc:error        stray '\211' in program
     1:1    error            gcc:error        stray '\34' in program
     1:1    error            gcc:error        stray '\4' in program
     1:1    error            gcc:error        stray '\20' in program
     1:1    error            gcc:error        stray '\177' in program
     1:1    error            gcc:error        stray '\1' in program
     1:1    error            gcc:error        stray '\7' in program
     1:1    error            gcc:error        stray '\211' in program
     1:1    error            gcc:error        stray '\34' in program
     1:1    error            gcc:error        stray '\4' in program
     1:1    error            gcc:error        stray '\20' in program
     1:1    error            gcc:error        stray '\177' in program
     1:1    error            gcc:error        stray '\1' in program
     1:1    error            gcc:error        stray '\7' in program
     1:1    error            gcc:error        stray '\211' in program
     1:1    error            gcc:error        stray '\34' in program
     1:1    error            gcc:error        stray '\4' in program
     1:1    error            gcc:error        stray '\20' in program
     1:1    error            gcc:error        stray '\177' in program
     1:1    error            gcc:error        stray '\1' in program
     1:1    error            gcc:error        stray '\7' in program
     1:1    error            gcc:error        stray '\211' in program
     1:1    error            gcc:error        stray '\34' in program
     1:1    error            gcc:error        stray '\4' in program
     1:1    error            gcc:error        stray '\20' in program
     1:1    error            gcc:error        stray '\177' in program
     1:1    error            gcc:error        stray '\1' in program
     1:1    error            gcc:error        stray '\7' in program
     1:1    error            gcc:error        stray '\211' in program
     1:1    error            gcc:error        stray '\34' in program
     1:1    error            gcc:error        stray '\4' in program
     1:1    error            gcc:error        stray '\20' in program
     1:1    error            gcc:error        'ELF' does not name a type
     1:1    error            gcc:error        'c' does not name a type
Though Im able to easily run and complie the file.
I have tried reinstalling gcc it did not help.
Update: This is happening only the directory where I have used vs code and saved custom build files in the directory/.vscode.

**Comment by kaste** [comment]
Good to know.
