### ISSUE TITLE
Linter uses C++ settings when using a non-standard C syntax

### ISSUE THREAD

**Issue by WolfBookyr** [jfcherng/SublimeLinter-contrib-gcc#14]
I use a custom C syntax, but as a result the linter defaults to using g++ and its associated C++ settings. It would be nice if there was a setting to specify extra syntaxes, e.g.
`"c_syntaxes": [ "Custom C" ]`
or if it selected which settings to use based on the scope of the syntax (i.e. source.c).

**Comment by jfcherng** [comment]
Before this plugin is re-written in pure SL4, you could add `Custom C` to SL's syntax mapping.

In `SublimeLinter.sublime-settings`,

```js
{
    // ...
    "syntax_map": {
        "custom c": "c",
    },
    // ...
}
```

**Comment by WolfBookyr** [comment]
I tried that, but it had no effect. Having seen your example I realised that my mistake was that I didn't use all lower case. I tried it again with all lower case and it works great.

Thank you!
