### ISSUE TITLE
SublimeLinter 4 compatibility

### ISSUE THREAD

**Issue by braver** [jfcherng/SublimeLinter-contrib-gcc#6]
In SL4 `persist.get_syntax()` is moved to `util.get_syntax()`. Please update this plugin like so: https://github.com/SublimeLinter/SublimeLinter-coffeelint/pull/28/files

**Comment by jfcherng** [comment]
@braver It's already done in https://github.com/jfcherng/SublimeLinter-contrib-gcc/blob/30a1df9ee239c04c18b0181d3c23e330ec847cdc/linter.py#L145-L153


Applied the new API :+1: 
https://github.com/jfcherng/SublimeLinter-contrib-gcc/blob/b0ab0d4b8595d92908ba54af2096c6ddfeeca93d/linter.py#L22-L27

**Comment by braver** [comment]
Yeah, the hardcoded version is new. Kinda handy too 😉
