### ISSUE TITLE
Sorry, we broke the interface again

### ISSUE THREAD

**Issue by braver** [jfcherng/SublimeLinter-contrib-gcc#7]
During development of SublimeLinter 4 we have recently been made aware of the "double import bug", where modules cannot import from the top level. This means we've had to move the VERSION attribute from the top to `/lint`. We're pushing out updates today. This should really only affect people testing SL4, but it would be good to stay aligned.

Your version check should be updated as such:

```py
return getattr(SublimeLinter.lint, 'VERSION', 3)
```

Sorry!

PS. We could move this repo into the [SublimeLinter group](https://github.com/SublimeLinter). I'll make sure you'll still have full access to it, but it would also allow me and other SL maintainers to make minor changes like this. If this sounds like a good idea to you, you can transfer the repo to me and I'll put  it in the group.

**Comment by jfcherng** [comment]
Got it. Fixed in `1.3.4`.

> PS. We could move this repo into the SublimeLinter group. I'll make sure you'll still have full access to it, but it would also allow me and other SL maintainers to make minor changes like this. If this sounds like a good idea to you, you can transfer the repo to me and I'll put it in the group.

Done.

**Comment by braver** [comment]
Awesome, thanks!
