### ISSUE TITLE
Update messages when pushing new releases

### ISSUE THREAD

**Issue by mandeep** [jfcherng/SublimeLinter-contrib-gcc#8]
Hi @jfcherng,

When a new build is released, the following message displays in Sublime Text:

```
SublimeLinter-contrib-iverilog has been updated. To see the changelog, visit
Preferences » Package Settings » SublimeLinter-contrib-iverilog » Changelog
```

Would it be possible to release new messages for every update?

Thanks!

**Comment by jfcherng** [comment]
You mean directly display the latest changelog and if the user want to check old changelog, go to the menu?

`SublimeLinter-contrib-iverilog` is my typo.

**Comment by mandeep** [comment]
Yeah, either that or show the entire changelog each update.

**Comment by jfcherng** [comment]
Going to display the changelog of the latest release.

**Comment by jfcherng** [comment]
By the way, there is no functional change in recent releases.

Most of them are compatibility about SublimeLinter 4 and moving this repo to be under the [SublimeLinter](https://github.com/SublimeLinter) organization (and change the package name from `SublimeLinter-contrib-gcc` to `SublimeLinter-gcc`).

**Comment by mandeep** [comment]
Thanks!
