### ISSUE TITLE
Local header not found

### ISSUE THREAD

**Issue by Nightcro** [jfcherng/SublimeLinter-contrib-gcc#9]
I have an issue with identifying local headers, i don't know why it is not working as intended https://imgur.com/V2WVWL0
The code works, it compiles.

**Comment by jfcherng** [comment]
I guess I could append the directory of the file, which is being edited, to the `include_dirs` automatically. I would test it later.

**Comment by Nightcro** [comment]
Forgot to mention
sublime version 3.0 build 3143
sublimelinter 4.0.0-rc.9.9.9.3
sublimelinter gcc 1.3.6

I already tried with these settings (Preferences->Settings->User-settings)
"SublimeLinter":
{
    "linters":
    {
        "gcc": {
            "c_executable": "gcc",
            "c_extra_flags": [
                "-fsyntax-only",
                "-std=c90"
            ],
            "c++_executable": "g++",
            "c++_extra_flags": [
                "-fsyntax-only",
                "-std=c++11"
            ],
            "include_dirs": [
                "${project_folder}/include",
                "${project_folder}"
            ]
        }
    }
},

Maybe i messed up something

**Comment by jfcherng** [comment]
This should have been fixed in the next version, i.e., `1.3.7` via https://github.com/SublimeLinter/SublimeLinter-gcc/commit/b247faaf3e7335e2456dd66d4999b5ef81f5e2cd.
